// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHzt72K4flpueVZcC4j4uBPGfeEpMbc4',
    appId: '1:632036056459:web:9130d4446f68f8bfcc638e',
    messagingSenderId: '632036056459',
    projectId: 'neurachat-2025',
    authDomain: 'neurachat-2025.firebaseapp.com',
    storageBucket: 'neurachat-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6n4p7i7bU1HQfbNeltvxVZy1WBuuCQQQ',
    appId: '1:632036056459:android:82d98660a5fa8d80cc638e',
    messagingSenderId: '632036056459',
    projectId: 'neurachat-2025',
    storageBucket: 'neurachat-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXv6Cy98hh9AVVBvs2JD4F_j7mtflVW4',
    appId: '1:632036056459:ios:8a9da7737593a07dcc638e',
    messagingSenderId: '632036056459',
    projectId: 'neurachat-2025',
    storageBucket: 'neurachat-2025.firebasestorage.app',
    iosBundleId: 'com.llama.bot.llamaBot',
  );

}